In [1]:
#Import libraries
import pandas as pd
import tensorflow as tf
import numpy as np

In [2]:
#Load data
Traindata = pd.read_csv('Data1/train.csv', header=None)
Vocab = pd.read_csv('Data1/vocab.csv', header=None)
Intents = pd.read_csv('Data1/intents.csv', header=None)
Trainintents = pd.read_csv('Data1/train_intent.csv', header=None)
Testdata = pd.read_csv('Data1/test.csv', header=None)
Slots = pd.read_csv('Data1/slots.csv', header=None)
Trainslots = pd.read_csv('Data1/train_slots.csv', header=None)

In [3]:
#create sentence for train data
sentences = []
for line in Traindata[0]:
    sentence = []
    for wordid in line.split():
        sentence.append(Vocab[0][int(wordid)])
    print(sentence)
    sentences.append(sentence)

['BOS', 'i', 'want', 'to', 'fly', 'from', 'boston', 'at', '838', 'am', 'and', 'arrive', 'in', 'denver', 'at', '1110', 'in', 'the', 'morning', 'EOS']
['BOS', 'what', 'flights', 'are', 'available', 'from', 'pittsburgh', 'to', 'baltimore', 'on', 'thursday', 'morning', 'EOS']
['BOS', 'what', 'is', 'the', 'arrival', 'time', 'in', 'san', 'francisco', 'for', 'the', '755', 'am', 'flight', 'leaving', 'washington', 'EOS']
['BOS', 'cheapest', 'airfare', 'from', 'tacoma', 'to', 'orlando', 'EOS']
['BOS', 'round', 'trip', 'fares', 'from', 'pittsburgh', 'to', 'philadelphia', 'under', '1000', 'dollars', 'EOS']
['BOS', 'i', 'need', 'a', 'flight', 'tomorrow', 'from', 'columbus', 'to', 'minneapolis', 'EOS']
['BOS', 'what', 'kind', 'of', 'aircraft', 'is', 'used', 'on', 'a', 'flight', 'from', 'cleveland', 'to', 'dallas', 'EOS']
['BOS', 'show', 'me', 'the', 'flights', 'from', 'pittsburgh', 'to', 'los', 'angeles', 'on', 'thursday', 'EOS']
['BOS', 'all', 'flights', 'from', 'boston', 'to', 'washington', 'EOS']

['BOS', 'is', 'there', 'an', 'early', 'morning', 'delta', 'airlines', 'flight', 'between', 'boston', 'and', 'washington', 'EOS']
['BOS', 'what', 'flights', 'from', 'orlando', 'to', 'tacoma', 'on', 'saturday', 'EOS']
['BOS', 'show', 'me', 'all', 'flights', 'both', 'direct', 'and', 'connecting', 'from', 'dallas', 'fort', 'worth', 'to', 'either', 'san', 'francisco', 'or', 'oakland', 'that', 'depart', 'after', '7', 'pm', 'EOS']
['BOS', 'give', 'me', 'flights', 'from', 'chicago', 'to', 'seattle', 'on', 'saturday', 'morning', 'EOS']
['BOS', 'okay', 'tell', 'me', 'what', 'the', 'earliest', 'flight', 'is', 'that', 'leaves', 'between', 'atlanta', 'and', 'denver', 'EOS']
['BOS', 'i', 'want', 'a', 'flight', 'from', 'toronto', 'to', 'montreal', 'that', 'leaves', 'early', 'friday', 'morning', 'EOS']
['BOS', 'what', 'first', 'class', 'flights', 'are', 'available', 'from', 'denver', 'to', 'baltimore', 'on', 'july', 'twenty', 'fifth', '1991', 'EOS']
['BOS', 'show', 'me', 'the', 'airlines', 'from', 'lo

['BOS', 'what', 'northwest', 'airline', 'flights', 'leave', 'denver', 'before', 'noon', 'EOS']
['BOS', 'from', 'denver', 'to', 'baltimore', 'EOS']
['BOS', 'i', "'m", 'trying', 'to', 'find', 'a', 'flight', 'from', 'columbus', 'to', 'phoenix', 'through', 'cincinnati', 'EOS']
['BOS', 'flight', 'information', 'between', 'washington', 'and', 'denver', 'on', 'september', 'third', 'EOS']
['BOS', 'what', 'flights', 'go', 'from', 'boston', 'to', 'denver', 'before', '10', 'am', 'EOS']
['BOS', 'flights', 'from', 'charlotte', 'to', 'baltimore', 'EOS']
['BOS', 'what', 'is', 'restriction', 'ap57', 'EOS']
['BOS', 'please', 'list', 'all', 'flights', 'from', 'dallas', 'to', 'philadelphia', 'on', 'monday', 'EOS']
['BOS', 'list', 'all', 'united', 'flights', 'from', 'boston', 'to', 'san', 'francisco', 'EOS']
['BOS', 'are', 'there', 'any', 'flights', 'from', 'boston', 'to', 'san', 'francisco', 'with', 'a', 'stopover', 'in', 'dallas', 'EOS']
['BOS', 'i', 'need', 'a', 'flight', 'from', 'san', 'francisco', 't

['BOS', 'i', 'want', 'a', 'flight', 'from', 'milwaukee', 'to', 'orlando', 'one', 'way', 'leaving', 'after', '5', 'pm', 'on', 'wednesday', 'EOS']
['BOS', 'which', 'flights', 'from', 'pittsburgh', 'to', 'atlanta', 'have', 'the', 'lowest', 'coach', 'class', 'fares', 'EOS']
['BOS', 'i', "'d", 'like', 'to', 'know', 'the', 'earliest', 'flight', 'from', 'boston', 'to', 'san', 'francisco', 'EOS']
['BOS', 'can', 'you', 'rent', 'a', 'car', 'at', 'stapleton', 'international', 'airport', 'in', 'denver', 'EOS']
['BOS', 'okay', 'i', "'d", 'like', 'a', 'flight', 'from', 'boston', 'to', 'san', 'francisco', 'that', 'leaves', 'before', '8', 'am', 'EOS']
['BOS', 'i', 'want', 'to', 'go', 'from', 'denver', 'to', 'atlanta', 'round', 'trip', 'and', 'make', 'a', 'stop', 'at', 'pittsburgh', 'may', 'i', 'have', 'the', 'cheapest', 'fare', 'EOS']
['BOS', 'is', 'there', 'a', 'delta', 'flight', 'from', 'boston', 'to', 'denver', 'EOS']
['BOS', 'i', 'would', 'like', 'to', 'fly', 'delta', 'airlines', 'from', 'atlanta'

['BOS', 'locate', 'flights', 'from', 'philadelphia', 'to', 'dallas', 'stopping', 'in', 'hartfield', 'EOS']
['BOS', 'what', 'kind', 'of', 'ground', 'transportation', 'is', 'there', 'in', 'philadelphia', 'EOS']
['BOS', 'i', "'m", 'trying', 'to', 'find', 'a', 'flight', 'from', 'kansas', 'city', 'to', 'burbank', 'on', 'saturday', 'the', 'twenty', 'second', 'EOS']
['BOS', 'flights', 'from', 'long', 'beach', 'to', 'nashville', 'EOS']
['BOS', 'show', 'flights', 'first', 'class', 'on', 'american', 'from', 'dallas', 'fort', 'worth', 'to', 'san', 'francisco', 'international', 'EOS']
['BOS', 'give', 'me', 'the', 'round', 'trip', 'coach', 'fare', 'from', 'dallas', 'to', 'baltimore', 'EOS']
['BOS', 'i', "'d", 'like', 'an', 'early', 'morning', 'weekday', 'flight', 'from', 'san', 'diego', 'to', 'phoenix', 'EOS']
['BOS', 'is', 'there', 'a', 'twa', 'flight', 'from', 'las', 'vegas', 'to', 'new', 'york', 'EOS']
['BOS', 'what', 'nonstop', 'flights', 'are', 'available', 'from', 'oakland', 'to', 'philadelph

['BOS', 'show', 'me', 'all', 'the', 'information', 'about', 'the', 'flight', 'from', 'baltimore', 'to', 'dallas', 'which', 'is', 'listed', 'dl', '1055', 'dl', '405', 'EOS']
['BOS', 'i', 'need', 'the', 'cost', 'of', 'a', 'ticket', 'going', 'from', 'denver', 'to', 'baltimore', 'a', 'first', 'class', 'ticket', 'on', 'united', 'airlines', 'EOS']
['BOS', 'which', 'nonstop', 'flight', 'from', 'atlanta', 'to', 'oakland', 'leaves', 'in', 'the', 'afternoon', 'and', 'arrives', 'at', '5', 'pm', 'EOS']
['BOS', 'i', 'need', 'a', 'flight', 'from', 'philadelphia', 'to', 'boston', 'EOS']
['BOS', 'what', 'is', 'the', 'ground', 'transportation', 'in', 'san', 'diego', 'EOS']
['BOS', 'is', 'there', 'a', 'flight', 'between', 'san', 'francisco', 'and', 'boston', 'with', 'a', 'stopover', 'in', 'dallas', 'fort', 'worth', 'EOS']
['BOS', 'show', 'me', 'all', 'flights', 'from', 'baltimore', 'to', 'san', 'francisco', 'EOS']
['BOS', 'i', 'would', 'like', 'a', 'flight', 'from', 'philadelphia', 'to', 'dallas', 'EOS'

['BOS', 'show', 'me', 'all', 'flights', 'from', 'montreal', 'EOS']
['BOS', 'list', 'types', 'of', 'planes', 'that', 'fly', 'between', 'pittsburgh', 'and', 'baltimore', 'EOS']
['BOS', 'are', 'there', 'any', 'flights', 'between', 'philadelphia', 'and', 'denver', 'EOS']
['BOS', 'train', 'to', 'newark', 'EOS']
['BOS', 'what', 'flights', 'from', 'atlanta', 'to', 'toronto', 'EOS']
['BOS', 'list', 'the', 'earliest', 'flights', 'from', 'st.', 'paul', 'to', 'houston', 'EOS']
['BOS', 'i', "'d", 'like', 'to', 'fly', 'from', 'boston', 'to', 'san', 'francisco', 'EOS']
['BOS', 'show', 'me', 'some', 'information', 'on', 'making', 'a', 'reservation', 'from', 'philadelphia', 'to', 'denver', 'on', 'sunday', 'EOS']
['BOS', 'list', 'all', 'united', 'flights', 'from', 'boston', 'to', 'san', 'francisco', 'with', 'fare', 'code', 'qx', 'EOS']
['BOS', 'leave', 'flight', 'from', 'boston', 'to', 'atlanta', 'leave', 'boston', 'approximately', '1', 'pm', 'EOS']
['BOS', 'i', "'d", 'like', 'the', 'cheapest', 'one', 

['BOS', 'which', 'delta', 'flights', 'fly', 'from', 'boston', 'to', 'philadelphia', 'EOS']
['BOS', 'show', 'me', 'the', 'flights', 'from', 'boston', 'to', 'oakland', 'EOS']
['BOS', 'bring', 'up', 'flights', 'from', 'milwaukee', 'to', 'orlando', 'on', 'wednesday', 'night', 'or', 'thursday', 'morning', 'EOS']
['BOS', 'flight', 'from', 'long', 'beach', 'to', 'columbus', 'on', 'twenty', 'seventh', 'EOS']
['BOS', 'what', 'flights', 'leave', 'seattle', 'on', 'sunday', 'on', 'continental', 'EOS']
['BOS', 'what', 'flights', 'go', 'from', 'san', 'francisco', 'to', 'boston', 'and', 'leave', 'after', '1', "o'clock", 'EOS']
['BOS', 'show', 'me', 'the', 'flights', 'from', 'denver', 'to', 'philadelphia', 'EOS']
['BOS', 'show', 'morning', 'flights', 'from', 'philadelphia', 'to', 'dallas', 'EOS']
['BOS', 'show', 'me', 'the', 'ground', 'transportation', 'schedule', 'in', 'philadelphia', 'in', 'the', 'morning', 'on', 'wednesday', 'EOS']
['BOS', 'what', 'flights', 'depart', 'baltimore', 'and', 'arrive', 

['BOS', 'what', 'are', 'the', 'flights', 'and', 'fares', 'from', 'atlanta', 'to', 'philadelphia', 'EOS']
['BOS', 'i', 'would', 'like', 'an', 'early', 'morning', 'nonstop', 'flight', 'from', 'new', 'york', 'to', 'las', 'vegas', 'on', 'february', 'twenty', 'eighth', 'EOS']
['BOS', 'describe', 'fare', 'code', 'qx', 'EOS']
['BOS', 'what', 'is', 'the', 'earliest', 'flight', 'on', 'friday', 'from', 'washington', 'to', 'san', 'francisco', 'EOS']
['BOS', 'american', 'flights', 'from', 'chicago', 'to', 'los', 'angeles', 'morning', 'EOS']
['BOS', 'show', 'all', 'flights', 'from', 'pittsburgh', 'to', 'oakland', 'EOS']
['BOS', 'list', 'all', 'flights', 'from', 'chicago', 'to', 'seattle', 'on', 'continental', 'airlines', 'which', 'depart', 'on', 'saturday', 'before', 'noon', 'and', 'include', 'a', 'meal', 'EOS']
['BOS', 'i', 'would', 'like', 'the', 'first', 'flight', 'into', 'houston', 'from', 'dallas', 'on', 'march', 'first', 'and', 'the', 'last', 'flight', 'from', 'houston', 'to', 'dallas', 'on',

['BOS', 'give', 'me', 'all', 'the', 'flights', 'from', 'new', 'york', 'to', 'miami', 'round', 'trip', 'with', 'costs', 'less', 'than', '466', 'dollars', 'EOS']
['BOS', 'what', 'is', 'the', 'seating', 'capacity', 'of', 'the', 'various', 'airplanes', 'that', 'united', 'airlines', 'uses', 'EOS']
['BOS', 'what', 'flights', 'from', 'kansas', 'city', 'to', 'chicago', 'leave', 'next', 'wednesday', 'returning', 'the', 'following', 'day', 'EOS']
['BOS', 'what', 'is', 'the', 'lowest', 'fare', 'from', 'denver', 'to', 'pittsburgh', 'EOS']
['BOS', 'could', 'you', 'list', 'for', 'me', 'the', 'flights', 'that', 'leave', 'oakland', 'on', 'sunday', 'and', 'arrive', 'in', 'dallas', 'EOS']
['BOS', 'i', 'would', 'like', 'to', 'book', 'a', 'flight', 'from', 'baltimore', 'to', 'san', 'francisco', 'before', '12', "o'clock", 'on', 'tuesday', 'EOS']
['BOS', 'flight', 'from', 'denver', 'to', 'san', 'francisco', 'in', 'the', 'afternoon', 'EOS']
['BOS', 'is', 'us', 'air', 'EOS']
['BOS', 'what', 'is', 'the', 'leas

['BOS', 'show', 'me', 'round', 'trips', 'from', 'houston', 'to', 'las', 'vegas', 'nonstop', 'EOS']
['BOS', 'please', 'list', 'all', 'flights', 'from', 'san', 'francisco', 'to', 'pittsburgh', 'on', 'sunday', 'EOS']
['BOS', 'i', 'want', 'a', 'flight', 'from', 'philadelphia', 'to', 'dallas', 'with', 'a', 'stop', 'in', 'atlanta', 'EOS']
['BOS', 'what', 'is', 'the', 'airfare', 'for', 'flights', 'from', 'denver', 'to', 'pittsburgh', 'on', 'delta', 'airline', 'EOS']
['BOS', 'do', 'you', 'have', 'any', 'flights', 'from', 'denver', 'to', 'baltimore', 'via', 'dallas', 'EOS']
['BOS', 'which', 'airlines', 'fly', 'into', 'and', 'out', 'of', 'denver', 'EOS']
['BOS', 'does', 'continental', 'fly', 'from', 'boston', 'to', 'san', 'francisco', 'with', 'a', 'stop', 'in', 'denver', 'EOS']
['BOS', 'is', 'there', 'a', 'delta', 'flight', 'from', 'denver', 'to', 'san', 'francisco', 'EOS']


In [4]:
#create sentences for test data
test_sentences = []
for line in Testdata[0]:
    test_sentence = []
    for wordid in line.split():
        test_sentence.append(Vocab[0][int(wordid)])
    #sentence = ' '.join(sentence)
    print(test_sentence)
    test_sentences.append(test_sentence)

['BOS', 'i', 'would', 'like', 'to', 'find', 'a', 'flight', 'from', 'charlotte', 'to', 'las', 'vegas', 'that', 'makes', 'a', 'stop', 'in', 'st.', 'louis', 'EOS']
['BOS', 'on', 'april', 'first', 'i', 'need', 'a', 'ticket', 'from', 'tacoma', 'to', 'san', 'jose', 'departing', 'before', '7', 'am', 'EOS']
['BOS', 'on', 'april', 'first', 'i', 'need', 'a', 'flight', 'going', 'from', 'phoenix', 'to', 'san', 'diego', 'EOS']
['BOS', 'i', 'would', 'like', 'a', 'flight', 'traveling', 'one', 'way', 'from', 'phoenix', 'to', 'san', 'diego', 'on', 'april', 'first', 'EOS']
['BOS', 'i', 'would', 'like', 'a', 'flight', 'from', 'orlando', 'to', 'salt', 'lake', 'city', 'for', 'april', 'first', 'on', 'delta', 'airlines', 'EOS']
['BOS', 'i', 'need', 'a', 'flight', 'from', 'toronto', 'to', 'newark', 'one', 'way', 'leaving', 'wednesday', 'evening', 'or', 'thursday', 'morning', 'EOS']
['BOS', 'monday', 'morning', 'i', 'would', 'like', 'to', 'fly', 'from', 'columbus', 'to', 'indianapolis', 'EOS']
['BOS', 'on', 'w

['BOS', 'ground', 'transportation', 'in', 'las', 'vegas', 'EOS']
['BOS', 'ground', 'transportation', 'for', 'las', 'vegas', 'EOS']
['BOS', 'las', 'vegas', 'to', 'baltimore', 'economy', 'EOS']
['BOS', 'las', 'vegas', 'to', 'baltimore', 'economy', 'EOS']
['BOS', 'baltimore', 'to', 'kansas', 'city', 'economy', 'EOS']
['BOS', 'what', 'airline', 'is', 'us', 'EOS']
['BOS', 'which', 'airline', 'is', 'us', 'EOS']
['BOS', 'which', 'airline', 'is', 'us', 'EOS']
['BOS', 'which', 'airline', 'is', 'us', 'EOS']
['BOS', 'which', 'airline', 'is', 'us', 'EOS']
['BOS', 'columbus', 'to', 'chicago', 'one', 'way', 'before', '10', 'am', 'EOS']
['BOS', 'what', 'airline', 'is', 'hp', 'EOS']
['BOS', 'st.', 'petersburg', 'to', 'detroit', 'EOS']
['BOS', 'from', 'milwaukee', 'to', 'orlando', 'one', 'way', 'after', '5', 'pm', 'wednesday', 'EOS']
['BOS', 'and', 'from', 'milwaukee', 'to', 'atlanta', 'before', '10', 'am', 'daily', 'EOS']
['BOS', 'what', 'airline', 'is', 'yx', 'EOS']
['BOS', 'show', 'me', 'all', 'flig

In [5]:
#create intents
intents = []
for intentid in Trainintents[0]:
    intents.append(Intents[0][int(intentid)])
print(intents)

['flight', 'flight', 'flight_time', 'airfare', 'airfare', 'flight', 'aircraft', 'flight', 'flight', 'ground_service', 'flight', 'flight', 'airport', 'flight', 'flight', 'airfare', 'ground_service', 'flight', 'flight', 'flight', 'flight', 'flight', 'flight', 'aircraft', 'airfare', 'flight', 'airline', 'flight', 'ground_service', 'flight', 'airfare', 'flight', 'flight', 'flight', 'flight', 'airfare', 'airline', 'flight', 'flight', 'flight', 'distance', 'flight', 'airline', 'airline', 'flight', 'airline', 'ground_service', 'abbreviation', 'flight', 'flight', 'flight_time', 'flight', 'flight', 'ground_fare', 'flight', 'abbreviation', 'flight', 'flight', 'flight', 'flight', 'flight', 'airline', 'flight', 'ground_service', 'airline', 'flight', 'flight', 'airport', 'flight', 'flight', 'abbreviation', 'flight', 'flight', 'flight', 'flight', 'aircraft', 'airfare', 'flight', 'flight', 'flight', 'flight', 'flight', 'flight', 'flight', 'airline', 'flight', 'flight', 'flight', 'flight', 'flight', '

In [6]:
#create slots
slots = []
for line in Trainslots[0]:
    slot = []
    for slotid in line.split():
        slot.append(Slots[0][int(slotid)])
    #slot = ' '.join(slot)
    print(slot)
    slots.append(slot)

['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-depart_time.time', 'I-depart_time.time', 'O', 'O', 'O', 'B-toloc.city_name', 'O', 'B-arrive_time.time', 'O', 'O', 'B-arrive_time.period_of_day', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'B-depart_date.day_name', 'B-depart_time.period_of_day', 'O']
['O', 'O', 'O', 'O', 'B-flight_time', 'I-flight_time', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'O', 'B-depart_time.time', 'I-depart_time.time', 'O', 'O', 'B-fromloc.city_name', 'O']
['O', 'B-cost_relative', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'B-round_trip', 'I-round_trip', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'B-cost_relative', 'B-fare_amount', 'I-fare_amount', 'O']
['O', 'O', 'O', 'O', 'O', 'B-depart_date.today_relative', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O'

['O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.airport_code', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'O', 'B-depart_date.day_name', 'O']
['O', 'O', 'O', 'O', 'B-flight_mod', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'B-airline_name', 'I-airline_name', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'B-depart_date.day_name', 'O']
['O', 'O', 'O', 'O', 'B-cost_relative', 'B-round_trip', 'I-round_trip', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'B-toloc.state_code', 'B-depart_time.time_relative', 'B-depart_time.time', 'I-depart_time.time', 'O', 'B-depart_date.month_name', 'B-depart_date.day_number', 'B-economy', 'I-economy', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'B-city_name', 'O']
['O', 'O', 'B-airline_name', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-tolo

['O', 'O', 'O', 'O', 'B-airline_code', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'O', 'O', 'O']
['O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'B-cost_relative', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'B-fromloc.state_name', 'I-fromloc.state_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'O', 'O', 'O', 'O', 'O', 'O', 'B-stoploc.city_name', 'I-stoploc.city_name', 'O']
['O', 'O', 'O', 'O', 'O', 'B-airline_name', 'O', 'O', 'B-connect', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'O', 'B-depart_time.time', 'O', 'O', 'B-depart_time.period_of_day', 'O']


['O', 'O', 'O', 'O', 'O', 'O', 'B-airline_code', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'O', 'O', 'O', 'B-stoploc.city_name', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-round_trip', 'I-round_trip', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'B-airline_name', 'I-airline_name', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'B-arrive_time.time_relative', 'B-arrive_time.time', 'I-arrive_time.time', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'B-depart_time.time_relative', 'B-depart_time.time', 'I-depart_time.time', 'I-depart_time.time', 'O']
['O', 'O', 'O', 'O', 'O', 'B-fare_basis_code', 'O', 'O']
['O', 'O', 'O', 'O', 'B-depart_time.period_of_day', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'B-class_type', 'I-class_type', 'O'

['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'B-depart_time.time_relative', 'B-depart_time.time', 'I-depart_time.time', 'B-depart_date.date_relative', 'B-depart_date.day_name', 'O', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'B-flight_time', 'I-flight_time', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'O', 'B-fare_basis_code', 'O', 'B-fare_basis_code', 'O']
['O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'B-depart_date.day_name', 'B-depart_time.period_of_day', 'O']
['O', 'O', 'O', 'O', 'B-cost_relative', 'B-connect', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'O', 'B-depart_date.month_name', 'B-depart_date.day_number', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'O', 'O', 'B-toloc.city_name', 'O', 'B-arrive_date.day_name', 'O']
['O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'B-dep

['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'B-or', 'B-toloc.city_name', 'O', 'B-fromloc.city_name', 'O', 'O', 'B-arrive_time.time_relative', 'B-arrive_time.time', 'I-arrive_time.time', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'B-depart_date.day_name', 'O']
['O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'B-depart_date.day_name', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'O', 'B-cost_relative', 'B-round_trip', 'I-round_trip', 'O', 'O', 'O', 'O', 'B-depart_date.day_name', 'O']
['O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'B-depart_date.day_name', 'O']
['O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'B-fromloc.city_name', 'O', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'B-depart_time.time_relative', 'B-depart_time.time', 

['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-city_name', 'O']
['O', 'O', 'O', 'O', 'B-cost_relative', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-toloc.city_name', 'O', 'B-fromloc.city_name', 'O']
['O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'B-toloc.state_name', 'O', 'B-depart_date.day_name', 'O']
['O', 'O', 'O', 'O', 'O', 'B-city_name', 'I-city_name', 'B-transport_type', 'O', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'O', 'B-airline_code', 'O', 'O', 'O', 'O', 'B-stoploc.city_name', 'O']
['O', 'O', 'O', 'O', 'O', 'B-cost_relative', 'B-round_trip', 'I-round_trip', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', '

['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-connect', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'O', 'B-depart_date.month_name', 'B-depart_date.day_number', 'O']
['O', 'B-depart_time.period_of_day', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'O', 'B-depart_date.day_name', 'B-depart_date.month_name', 'B-depart_date.day_number', 'O', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'O', 'B-arrive_time.time_relative', 'B-arrive_time.time', 'I-arrive_time.time', 'O', 'O', 'B-arrive_time.period_of_day', 'O']
['O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'B-airline_name', 'O', 'O', 'B-fromloc.city_name', 'B-depart_time.time_relative', 'B-depart_time.time', 'O']
['O', 'O', 'O', 'O', 'O', 'B-fromloc.airpor

['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'B-depart_date.day_name', 'B-depart_date.month_name', 'B-depart_date.day_number', 'O', 'B-arrive_time.time_relative', 'B-arrive_time.time', 'O']
['O', 'O', 'O', 'O', 'O', 'B-fare_basis_code', 'O', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'O', 'O', 'O', 'B-stoploc.city_name', 'I-stoploc.city_name', 'I-stoploc.city_name', 'O']
['O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'B-toloc.state_code', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-flight_mod', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'B-depart_time.period_of_day', 'O']
['O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'B-depart_date.day_name', 'O']
['O', 'O', 'O', 'O', 'B-fare_basis_code', 'O', 'B-mod', 'O', 'B-class_ty

['O', 'O', 'B-airline_name', 'O', 'O', 'B-city_name', 'O']
['O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'O', 'O', 'B-toloc.city_name', 'O', 'B-arrive_time.time', 'I-arrive_time.time', 'O', 'O', 'B-arrive_time.period_of_day', 'O']
['O', 'O', 'O', 'O', 'O', 'B-fare_basis_code', 'O', 'O']
['O', 'B-round_trip', 'I-round_trip', 'B-class_type', 'I-class_type', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O']
['O', 'B-depart_date.month_name', 'B-depart_date.day_number', 'O', 'O', 'O', 'O', 'O', 'O', 'B-round_trip', 'I-round_trip', 'O', 'O', 'B-class_type', 'I-class_type', 'O', 'B-airline_name', 'I-airline_name', 'O', 'O', 'B-fromloc.city_name', 'O', 'O', 'B-toloc.city_name', 'O']
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'B-toloc.country_name', 'O', 'O', 'B-depart_date.day_name', 'O']
['O', 'O', 'O', 'O', 'B-fare_basis_code', 'O']
['O', 'O', 'O', 'O', 'B-cost_relative', 'O', 'O', '

In [7]:
test_sentences = [t[:-1] for t in test_sentences]
length = 50
test_sin = []
test_sout = []
test_intent = []
for line in range(len(test_sentences)):
    temp = test_sentences[line]
    if len(temp) < length:
        temp.append('EOS')
        while len(temp) < length:
            temp.append('<PAD>')
    else:
        temp = temp[:length]
        temp.append('EOS')
    test_sin.append(temp)
    count=0
    temp=[]
    while count<length:
        temp.append('<PAD')
        count+=1
    test_sout.append(temp)
    temp=""
    test_intent.append(temp)
test_data = list(zip(test_sin,test_sout,test_intent))
print(test_data[0])

(['BOS', 'i', 'would', 'like', 'to', 'find', 'a', 'flight', 'from', 'charlotte', 'to', 'las', 'vegas', 'that', 'makes', 'a', 'stop', 'in', 'st.', 'louis', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'], ['<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD', '<PAD'], '')


In [12]:
#To index
#def to_index(train, word2index, slot2index, intent2index):
new_test_data = []
for sin, sout, intent in test_data:
    sin_ix = list(map(lambda i: word2index[i] if i in word2index else word2index["<UNK>"],sin))
    true_length = sin.index('EOS')
    sout_ix = list(map(lambda i: tag2index[i] if i in tag2index else tag2index["<UNK>"],sout))
    intent_ix = intent2index[intent] if intent in intent2index else intent2index["<UNK>"]
    new_test_data.append([sin_ix, true_length, sout_ix, intent_ix])
#    return new_train
#index_train = to_index(train_data_ed, word2index, slot2index, intent2index)
#index_test = to_index(test_data_ed, word2index, slot2index, intent2index)
print('TRAINING AND TESTING DATA STRUCTURE:')
print('ORIGINAL_index | UNPADDED_seqLength | LABELED_index | INDENT\n')
print(new_test_data[0])

TRAINING AND TESTING DATA STRUCTURE:
ORIGINAL_index | UNPADDED_seqLength | LABELED_index | INDENT

[[2, 767, 787, 262, 212, 311, 107, 89, 763, 553, 212, 462, 197, 879, 194, 107, 559, 808, 661, 681, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 20, [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 0]


In [9]:
'''test_sentences = [t[:-1] for t in test_sentences]
length = 50
test_sin = []
test_sout = []
for line in range(len(test_sentences)):
    temp = test_sentences[line]
    #print(len(temp))
    if len(temp) < length:
        temp.append('EOS')
        while len(temp) < length:
            temp.append('<PAD>')
    else:
        temp = temp[:length]
        temp.append('EOS')
    test_sin.append(temp)
test_data = list(zip(test_sin))
print(test_data[0])'''

"test_sentences = [t[:-1] for t in test_sentences]\nlength = 50\ntest_sin = []\ntest_sout = []\nfor line in range(len(test_sentences)):\n    temp = test_sentences[line]\n    #print(len(temp))\n    if len(temp) < length:\n        temp.append('EOS')\n        while len(temp) < length:\n            temp.append('<PAD>')\n    else:\n        temp = temp[:length]\n        temp.append('EOS')\n    test_sin.append(temp)\ntest_data = list(zip(test_sin))\nprint(test_data[0])"

In [10]:
sentences = [t[:-1] for t in sentences]
length = 50
sin = []
sout = []
for line in range(len(sentences)):
    temp = sentences[line]
    #print(len(temp))
    if len(temp) < length:
        temp.append('EOS')
        while len(temp) < length:
            temp.append('<PAD>')
    else:
        temp = temp[:length]
        temp.append('EOS')
    sin.append(temp)
        
for line1 in range(len(slots)): 
    temp1 = slots[line1]
    if len(temp1) < length:
        while len(temp1) < length:
            temp1.append('<PAD>')
    else:
        temp1 = temp1[:length]
        #temp1.append('<EOS>')
    sout.append(temp1)
data = list(zip(sin, sout, intents))
print(data[0])

(['BOS', 'i', 'want', 'to', 'fly', 'from', 'boston', 'at', '838', 'am', 'and', 'arrive', 'in', 'denver', 'at', '1110', 'in', 'the', 'morning', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'], ['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-depart_time.time', 'I-depart_time.time', 'O', 'O', 'O', 'B-toloc.city_name', 'O', 'B-arrive_time.time', 'O', 'O', 'B-arrive_time.period_of_day', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'], 'flight')


In [13]:
#from keras.layers import Dense, Activation, Flatten
flatten = lambda l: [item for sublist in l for item in sublist]
index_seq2slot = lambda s, index2slot: [index2slot[i] for i in s]
index_seq2word = lambda s, index2word: [index2word[i] for i in s]
seq_in, seq_out, intent = list(zip(*data))
vocab = set(flatten(seq_in))
slot_tag = set(flatten(seq_out))
intent_tag = set(intent)
# generate word2index
word2index = {'<PAD>': 0, '<UNK>': 1, 'BOS': 2, 'EOS': 3}
for token in vocab:
    if token not in word2index.keys():
        word2index[token] = len(word2index)

# generate index2word
index2word = {v: k for k, v in word2index.items()}

# generate tag2index
tag2index = {'<PAD>': 0, '<UNK>': 1, "O": 2}
for tag in slot_tag:
    if tag not in tag2index.keys():
        tag2index[tag] = len(tag2index)

# generate index2tag
index2tag = {v: k for k, v in tag2index.items()}

# generate intent2index
intent2index = {'<UNK>': 0}
for ii in intent_tag:
    if ii not in intent2index.keys():
        intent2index[ii] = len(intent2index)

# generate index2intent
index2intent = {v: k for k, v in intent2index.items()}
#return word2index, index2word, tag2index, index2tag, intent2index, index2intent


#word2index, index2word, slot2index, index2slot, intent2index, index2intent = \
#        get_info_from_training_data(train_data_ed)
index2tag

{0: '<PAD>',
 1: '<UNK>',
 2: 'O',
 3: 'I-fromloc.state_name',
 4: 'B-toloc.state_code',
 5: 'I-depart_date.day_number',
 6: 'B-or',
 7: 'B-depart_date.day_number',
 8: 'I-fare_basis_code',
 9: 'B-arrive_date.day_name',
 10: 'B-city_name',
 11: 'B-time_relative',
 12: 'B-round_trip',
 13: 'B-return_date.day_number',
 14: 'I-class_type',
 15: 'B-flight_stop',
 16: 'B-airline_name',
 17: 'B-depart_time.start_time',
 18: 'B-depart_time.time_relative',
 19: 'I-time',
 20: 'B-today_relative',
 21: 'I-arrive_time.period_of_day',
 22: 'B-fare_basis_code',
 23: 'I-fromloc.airport_name',
 24: 'B-flight_time',
 25: 'I-round_trip',
 26: 'B-depart_date.year',
 27: 'B-connect',
 28: 'I-depart_date.today_relative',
 29: 'B-depart_date.month_name',
 30: 'I-toloc.city_name',
 31: 'B-state_code',
 32: 'B-class_type',
 33: 'B-depart_time.end_time',
 34: 'B-arrive_date.day_number',
 35: 'I-meal_code',
 36: 'I-flight_mod',
 37: 'B-meal_code',
 38: 'I-airport_name',
 39: 'B-stoploc.airport_name',
 40: 'B-f

In [14]:
#To index
#def to_index(train, word2index, slot2index, intent2index):
new_data = []
for sin, sout, intent in data:
    sin_ix = list(map(lambda i: word2index[i] if i in word2index else word2index["<UNK>"],sin))
    true_length = sin.index('EOS')
    sout_ix = list(map(lambda i: tag2index[i] if i in tag2index else tag2index["<UNK>"],sout))
    intent_ix = intent2index[intent] if intent in intent2index else intent2index["<UNK>"]
    new_data.append([sin_ix, true_length, sout_ix, intent_ix])
#    return new_train
#index_train = to_index(train_data_ed, word2index, slot2index, intent2index)
#index_test = to_index(test_data_ed, word2index, slot2index, intent2index)
train_data=new_data[:3500]
val_data=new_data[3500:]
print('TRAINING AND TESTING DATA STRUCTURE:')
print('ORIGINAL_index | UNPADDED_seqLength | LABELED_index | INDENT\n')
print(new_data[0])
print(train_data[0])
print(val_data[0])

TRAINING AND TESTING DATA STRUCTURE:
ORIGINAL_index | UNPADDED_seqLength | LABELED_index | INDENT

[[2, 767, 354, 212, 153, 763, 307, 374, 538, 168, 680, 786, 808, 669, 374, 119, 808, 173, 414, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 19, [2, 2, 2, 2, 2, 2, 81, 2, 106, 55, 2, 2, 2, 79, 2, 53, 2, 2, 101, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 9]
[[2, 767, 354, 212, 153, 763, 307, 374, 538, 168, 680, 786, 808, 669, 374, 119, 808, 173, 414, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 19, [2, 2, 2, 2, 2, 2, 81, 2, 106, 55, 2, 2, 2, 79, 2, 53, 2, 2, 101, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 9]
[[2, 72, 679, 173, 66, 879, 153, 255, 753, 862, 468, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 11, [2, 2, 2, 2, 2

In [15]:
import tensorflow as tf
import random

input_steps = 50      # specified length size
embedding_size = 64
hidden_size = 100
n_layers = 2
batch_size = 16
vocab_size = 893
slot_size = 125
intent_size = 22
epoch_num = 15

######  E N C O D E R   A N D   D E C O D E R  ######
encoder_inputs = tf.placeholder(tf.int32,[input_steps,batch_size],name='encoder_inputs')

# The actual length of each sentence without padding
encoder_inputs_actual_length = tf.placeholder(tf.int32, [batch_size],
                                                   name='encoder_inputs_actual_length')

decoder_targets = tf.placeholder(tf.int32, [batch_size, input_steps],
                                      name='decoder_targets')

intent_targets = tf.placeholder(tf.int32, [batch_size],
                                     name='intent_targets')

######  E M B E D D I N G  ######
embeddings = tf.Variable(tf.random_uniform([vocab_size, embedding_size],
                                           -0.1, 0.1), dtype=tf.float32, name="embedding")

encoder_inputs_embedded = tf.nn.embedding_lookup(embeddings, encoder_inputs)
encoder_inputs_embedded

<tf.Tensor 'embedding_lookup:0' shape=(50, 16, 64) dtype=float32>

In [16]:
#ENCODER
from tensorflow.contrib.rnn import LSTMCell, LSTMStateTuple

# Use a single LSTM cell
encoder_f_cell = LSTMCell(hidden_size)
encoder_b_cell = LSTMCell(hidden_size)

# The size of the following four variables: T*B*D, T*B*D, B*D, B*D
(encoder_fw_outputs, encoder_bw_outputs), (encoder_fw_final_state, encoder_bw_final_state) = \
    tf.nn.bidirectional_dynamic_rnn(cell_fw=encoder_f_cell,
                                    cell_bw=encoder_b_cell,
                                    inputs=encoder_inputs_embedded,
                                    sequence_length=encoder_inputs_actual_length,
                                    dtype=tf.float32, time_major=True)
encoder_outputs = tf.concat((encoder_fw_outputs, encoder_bw_outputs), 2)

encoder_final_state_c = tf.concat(
    (encoder_fw_final_state.c, encoder_bw_final_state.c), 1)

encoder_final_state_h = tf.concat(
    (encoder_fw_final_state.h, encoder_bw_final_state.h), 1)

encoder_final_state = LSTMStateTuple(
    c=encoder_final_state_c,
    h=encoder_final_state_h)

print("encoder_outputs: ", encoder_outputs)
print("encoder_outputs[0]: ", encoder_outputs[0])
print("encoder_final_state_c: ", encoder_final_state_c)

Instructions for updating:
seq_dim is deprecated, use seq_axis instead
Instructions for updating:
batch_dim is deprecated, use batch_axis instead
encoder_outputs:  Tensor("concat:0", shape=(50, 16, 200), dtype=float32)
encoder_outputs[0]:  Tensor("strided_slice:0", shape=(16, 200), dtype=float32)
encoder_final_state_c:  Tensor("concat_1:0", shape=(16, 200), dtype=float32)


In [17]:
decoder_lengths = encoder_inputs_actual_length

slot_W = tf.Variable(tf.random_uniform([hidden_size * 2, slot_size], -1, 1),
                             dtype=tf.float32, name="slot_W")
slot_b = tf.Variable(tf.zeros([slot_size]), dtype=tf.float32, name="slot_b")
intent_W = tf.Variable(tf.random_uniform([hidden_size * 2, intent_size], -0.1, 0.1),
                               dtype=tf.float32, name="intent_W")
intent_b = tf.Variable(tf.zeros([intent_size]), dtype=tf.float32, name="intent_b")

# start intent
intent_logits = tf.add(tf.matmul(encoder_final_state_h, intent_W), intent_b)
intent = tf.argmax(intent_logits, axis=1)

sos_time_slice = tf.ones([batch_size], dtype=tf.int32, name='SOS') * 2
sos_step_embedded = tf.nn.embedding_lookup(embeddings, sos_time_slice)
pad_step_embedded = tf.zeros([batch_size, hidden_size * 2 + embedding_size],
                             dtype=tf.float32)

In [18]:
def initial_fn():
    initial_elements_finished = (0 >= decoder_lengths)  # all False at the initial step
    initial_input = tf.concat((sos_step_embedded, encoder_outputs[0]), 1)
    return initial_elements_finished, initial_input

def sample_fn(time, outputs, state):
    # Select logit's largest subscript as sample
    prediction_id = tf.to_int32(tf.argmax(outputs, axis=1))
    return prediction_id

def next_inputs_fn(time, outputs, state, sample_ids):
    # The output class on the previous time node, gets embedding and enters as the next time node
    pred_embedding = tf.nn.embedding_lookup(embeddings, sample_ids)
    # The input is h_i+o_{i-1}+c_i
    next_input = tf.concat((pred_embedding, encoder_outputs[time]), 1)
    elements_finished = (time >= decoder_lengths)  # this operation produces boolean tensor of [batch_size]
    all_finished = tf.reduce_all(elements_finished)  # -> boolean scalar
    next_inputs = tf.cond(all_finished, lambda: pad_step_embedded, lambda: next_input)
    next_state = state
    return elements_finished, next_inputs, next_state

# Define your own helper
my_helper = tf.contrib.seq2seq.CustomHelper(initial_fn, sample_fn, next_inputs_fn)

def decode(helper, scope, reuse=None):
    with tf.variable_scope(scope, reuse=reuse):
        memory = tf.transpose(encoder_outputs, [1, 0, 2])
        attention_mechanism = tf.contrib.seq2seq.BahdanauAttention(
            num_units=hidden_size, memory=memory,
            memory_sequence_length=encoder_inputs_actual_length)
        cell = tf.contrib.rnn.LSTMCell(num_units=hidden_size * 2)
        attn_cell = tf.contrib.seq2seq.AttentionWrapper(
            cell, attention_mechanism, attention_layer_size=hidden_size)
        out_cell = tf.contrib.rnn.OutputProjectionWrapper(
            attn_cell, slot_size, reuse=reuse
        )
        decoder = tf.contrib.seq2seq.BasicDecoder(
            cell=out_cell, helper=helper,
            initial_state=out_cell.zero_state(
                dtype=tf.float32, batch_size=batch_size))
        # initial_state=encoder_final_state)
        final_outputs, final_state, final_sequence_lengths = tf.contrib.seq2seq.dynamic_decode(
            decoder=decoder, output_time_major=True,
            impute_finished=True, maximum_iterations=input_steps
        )
        return final_outputs
    
outputs = decode(my_helper, 'decode')

print("outputs: ", outputs)
print("outputs.rnn_output: ", outputs.rnn_output)
print("outputs.sample_id: ", outputs.sample_id)

outputs:  BasicDecoderOutput(rnn_output=<tf.Tensor 'decode/decoder/TensorArrayStack/TensorArrayGatherV3:0' shape=(?, 16, 125) dtype=float32>, sample_id=<tf.Tensor 'decode/decoder/TensorArrayStack_1/TensorArrayGatherV3:0' shape=(?, 16) dtype=int32>)
outputs.rnn_output:  Tensor("decode/decoder/TensorArrayStack/TensorArrayGatherV3:0", shape=(?, 16, 125), dtype=float32)
outputs.sample_id:  Tensor("decode/decoder/TensorArrayStack_1/TensorArrayGatherV3:0", shape=(?, 16), dtype=int32)


In [19]:
decoder_prediction = outputs.sample_id
decoder_max_steps, decoder_batch_size, decoder_dim = tf.unstack(tf.shape(outputs.rnn_output))
decoder_targets_time_majored = tf.transpose(decoder_targets, [1, 0])
decoder_targets_true_length = decoder_targets_time_majored[:decoder_max_steps]
print("decoder_targets_true_length: ", decoder_targets_true_length)

decoder_targets_true_length:  Tensor("strided_slice_1:0", shape=(?, 16), dtype=int32)


In [20]:
# Define mask so that padding does not count towards loss
mask = tf.to_float(tf.not_equal(decoder_targets_true_length, 0))

# Defining the loss of the slot label
loss_slot = tf.contrib.seq2seq.sequence_loss(
    outputs.rnn_output, decoder_targets_true_length, weights=mask)

# Defining loss of intent classification
cross_entropy = tf.nn.softmax_cross_entropy_with_logits(
    labels=tf.one_hot(intent_targets, depth=intent_size, dtype=tf.float32),
    logits=intent_logits)
loss_intent = tf.reduce_mean(cross_entropy)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.



In [21]:
# METRICS FUNCTIONS
import numpy.ma as ma
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

loss = loss_slot + loss_intent
optimizer = tf.train.AdamOptimizer(name="a_optimizer")
grads, vars = zip(*optimizer.compute_gradients(loss))
gradients, _ = tf.clip_by_global_norm(grads, 5)  # clip gradients
train_op = optimizer.apply_gradients(zip(grads, vars))

def step(sess, mode, trarin_batch):
    #print("in step function")
    """ perform each batch"""
    #print("here")
    if mode not in ['train', 'test']:
        print >> sys.stderr, 'mode is not supported'
        sys.exit(1)
    #print("here1")
    unziped = list(zip(*trarin_batch))
    #print(unziped[3])
    #print("here2")
    if mode == 'train':
        #print("here3")
        output_feeds = [train_op, loss, decoder_prediction,
                        intent]
        #print("here4")
        feed_dict = {encoder_inputs: np.transpose(unziped[0], [1, 0]),
                     encoder_inputs_actual_length: unziped[1],
                     decoder_targets: unziped[2],
                     intent_targets: unziped[3]}
        #print("here5")
    if mode in ['test']:
        output_feeds = [decoder_prediction, intent]
        feed_dict = {encoder_inputs: np.transpose(unziped[0], [1, 0]),
                     encoder_inputs_actual_length: unziped[1]}
    #print("here6")
    results = sess.run(output_feeds, feed_dict=feed_dict)
    #print("here7")
    return results

def accuracy_score(true_data, pred_data, true_length=None):
    true_data = np.array(true_data)
    pred_data = np.array(pred_data)
    assert true_data.shape == pred_data.shape
    if true_length is not None:
        val_num = np.sum(true_length)
        assert val_num != 0
        res = 0
        for i in range(true_data.shape[0]):
            res += np.sum(true_data[i, :true_length[i]] == pred_data[i, :true_length[i]])
    else:
        val_num = np.prod(true_data.shape)
        assert val_num != 0
        res = np.sum(true_data == pred_data)
    res /= float(val_num)
    return res

def get_data_from_sequence_batch(true_batch, pred_batch, padding_token):
    """Extract data from a sequence of batches：
    [[3,1,2,0,0,0],[5,2,1,4,0,0]] -> [3,1,2,5,2,1,4]"""
    true_ma = ma.masked_equal(true_batch, padding_token)
    #print("pred_batch")
    #print(pred_batch)
    #print("true_ma.mask")
    #print(true_ma.mask)
    pred_ma = ma.masked_array(pred_batch, true_ma.mask)
    true_ma = true_ma.flatten()
    pred_ma = pred_ma.flatten()
    true_ma = true_ma[~true_ma.mask]
    pred_ma = pred_ma[~pred_ma.mask]
    return true_ma, pred_ma

def f1_for_sequence_batch(true_batch, pred_batch, average="micro", padding_token=0):
    true, pred = get_data_from_sequence_batch(true_batch, pred_batch, padding_token)
    labels = list(set(true))
    return f1_score(true, pred, labels=labels, average=average)

def accuracy_for_sequence_batch(true_batch, pred_batch, padding_token=0):
    true, pred = get_data_from_sequence_batch(true_batch, pred_batch, padding_token)
    return accuracy_score(true, pred)

def getBatch(batch_size, train_data):
    random.shuffle(train_data)
    sindex = 0
    eindex = batch_size
    while eindex < len(train_data):
        batch = train_data[sindex:eindex]
        temp = eindex
        eindex = eindex + batch_size
        sindex = temp
        yield batch
        
def getBatch2(batch_size, train_data):
    sindex = 0
    eindex = batch_size
    while eindex < len(train_data):
        batch = train_data[sindex:eindex]
        temp = eindex
        eindex = eindex + batch_size
        sindex = temp
        yield batch

In [22]:
#print(train_data[0])
#print(val_data[0])
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for epoch in range(epoch_num):
    print(epoch)
    mean_loss = 0.0
    train_loss = 0.0
    print(epoch)
    for i, batch in enumerate(getBatch(batch_size, train_data)):
        # Perform a batch training
        #print(batch)
        _, loss_v, decoder_prediction_v, intent_v = step(sess, "train", batch)
        #print("1")
        mean_loss += loss_v
        train_loss += loss_v
        if i % 30 == 0:
            if i > 0:
                mean_loss = mean_loss / 30.0
            print('Average train loss at epoch %d, step %d: %f' % (epoch, i, mean_loss))
            mean_loss = 0
    train_loss /= (i + 1)
    print("[Epoch {}] Average train loss: {}".format(epoch, train_loss))

    # One epoch per training, test once
    pred_slots = []
    for j, batch in enumerate(getBatch(batch_size, val_data)):
        #print(batch)
        decoder_prediction_v, intent_v = step(sess, "test", batch)
        decoder_prediction_v = np.transpose(decoder_prediction_v, [1, 0])
        if j == 0:
            index = random.choice(range(len(batch)))
            print("Input Sentence        : ", index_seq2word(batch[index][0], index2word))
            print("Slot Truth            : ", index_seq2slot(batch[index][2], index2tag))
            print("Slot Prediction       : ", index_seq2slot(decoder_prediction_v[index], index2tag))
            print("Intent Truth          : ", index2intent[batch[index][3]])
            print("Intent Prediction     : ", index2intent[intent_v[index]])
        slot_pred_length = list(np.shape(decoder_prediction_v))[1]
        pred_padded = np.lib.pad(decoder_prediction_v, ((0, 0), (0, input_steps-slot_pred_length)),
                                 mode="constant", constant_values=0)
        pred_slots.append(pred_padded)
        true_slot = np.array((list(zip(*batch))[2]))
        true_length = np.array((list(zip(*batch))[1]))
        true_slot = true_slot[:, :slot_pred_length]
        slot_acc = accuracy_score(true_slot, decoder_prediction_v, true_length)
        intent_acc = accuracy_score(list(zip(*batch))[3], intent_v)
        print("slot accuracy: {}, intent accuracy: {}".format(slot_acc, intent_acc))
    
    pred_slots_a = np.vstack(pred_slots)
    true_slots_a = np.array(list(zip(*val_data))[2])[:pred_slots_a.shape[0]]
    #print("true_slots_a")
    print(true_slots_a)
    #print("pred_slots_a")
    print(pred_slots_a)
    print("F1 score for epoch {}: {}".format(epoch, f1_for_sequence_batch(true_slots_a, pred_slots_a)))

0
0
Average train loss at epoch 0, step 0: 7.923361
Average train loss at epoch 0, step 30: 4.524991
Average train loss at epoch 0, step 60: 2.367069
Average train loss at epoch 0, step 90: 2.380421
Average train loss at epoch 0, step 120: 2.304374
Average train loss at epoch 0, step 150: 2.182121
Average train loss at epoch 0, step 180: 2.147364
Average train loss at epoch 0, step 210: 1.807874
[Epoch 0] Average train loss: 2.525161258671262
Input Sentence        :  ['BOS', 'show', 'me', 'round', 'trip', 'tickets', 'from', 'new', 'york', 'to', 'miami', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>']
Slot Truth            :  ['O', 'O', 'O', 'B-round_trip', 'I-round_trip', 'O', 'O', 'B-froml

slot accuracy: 0.8461538461538461, intent accuracy: 0.875
slot accuracy: 0.8, intent accuracy: 1.0
slot accuracy: 0.7916666666666666, intent accuracy: 0.875
slot accuracy: 0.863905325443787, intent accuracy: 1.0
slot accuracy: 0.8166666666666667, intent accuracy: 0.9375
slot accuracy: 0.8342245989304813, intent accuracy: 0.875
slot accuracy: 0.8260869565217391, intent accuracy: 0.9375
slot accuracy: 0.7553191489361702, intent accuracy: 0.875
slot accuracy: 0.8387096774193549, intent accuracy: 0.875
slot accuracy: 0.8222222222222222, intent accuracy: 0.9375
slot accuracy: 0.8333333333333334, intent accuracy: 0.9375
slot accuracy: 0.7963800904977375, intent accuracy: 0.9375
slot accuracy: 0.7961165048543689, intent accuracy: 0.8125
slot accuracy: 0.84, intent accuracy: 0.9375
slot accuracy: 0.8293838862559242, intent accuracy: 0.875
slot accuracy: 0.8412698412698413, intent accuracy: 0.875
slot accuracy: 0.8157894736842105, intent accuracy: 1.0
slot accuracy: 0.8272251308900523, intent a

slot accuracy: 0.868020304568528, intent accuracy: 1.0
slot accuracy: 0.8102564102564103, intent accuracy: 0.8125
slot accuracy: 0.8636363636363636, intent accuracy: 0.8125
slot accuracy: 0.9529411764705882, intent accuracy: 0.8125
slot accuracy: 0.8947368421052632, intent accuracy: 0.875
slot accuracy: 0.8378378378378378, intent accuracy: 0.875
slot accuracy: 0.8476190476190476, intent accuracy: 0.8125
slot accuracy: 0.8144329896907216, intent accuracy: 0.9375
slot accuracy: 0.8775510204081632, intent accuracy: 1.0
slot accuracy: 0.8604651162790697, intent accuracy: 1.0
slot accuracy: 0.8702702702702703, intent accuracy: 0.6875
slot accuracy: 0.8490566037735849, intent accuracy: 0.9375
slot accuracy: 0.9010989010989011, intent accuracy: 1.0
slot accuracy: 0.8663594470046083, intent accuracy: 0.9375
slot accuracy: 0.8537735849056604, intent accuracy: 0.875
slot accuracy: 0.8535353535353535, intent accuracy: 0.75
slot accuracy: 0.8571428571428571, intent accuracy: 0.875
slot accuracy: 0

slot accuracy: 0.8969072164948454, intent accuracy: 0.75
slot accuracy: 0.85, intent accuracy: 0.875
slot accuracy: 0.8391959798994975, intent accuracy: 0.9375
slot accuracy: 0.8502202643171806, intent accuracy: 0.875
slot accuracy: 0.83, intent accuracy: 0.9375
slot accuracy: 0.8290155440414507, intent accuracy: 0.9375
slot accuracy: 0.8620689655172413, intent accuracy: 1.0
slot accuracy: 0.8516949152542372, intent accuracy: 0.875
slot accuracy: 0.8762886597938144, intent accuracy: 0.875
slot accuracy: 0.8703703703703703, intent accuracy: 0.875
slot accuracy: 0.8557692307692307, intent accuracy: 0.9375
slot accuracy: 0.897196261682243, intent accuracy: 0.875
slot accuracy: 0.8855721393034826, intent accuracy: 0.9375
slot accuracy: 0.8564356435643564, intent accuracy: 0.8125
slot accuracy: 0.8486238532110092, intent accuracy: 0.9375
slot accuracy: 0.8918918918918919, intent accuracy: 1.0
slot accuracy: 0.8546255506607929, intent accuracy: 0.9375
slot accuracy: 0.84, intent accuracy: 0.

slot accuracy: 0.918918918918919, intent accuracy: 0.9375
slot accuracy: 0.8771929824561403, intent accuracy: 0.9375
slot accuracy: 0.8468468468468469, intent accuracy: 0.9375
slot accuracy: 0.908256880733945, intent accuracy: 1.0
slot accuracy: 0.9565217391304348, intent accuracy: 1.0
slot accuracy: 0.8837209302325582, intent accuracy: 1.0
slot accuracy: 0.9214659685863874, intent accuracy: 0.9375
slot accuracy: 0.9217877094972067, intent accuracy: 0.8125
slot accuracy: 0.9393939393939394, intent accuracy: 0.8125
slot accuracy: 0.933649289099526, intent accuracy: 0.9375
slot accuracy: 0.8826291079812206, intent accuracy: 0.9375
slot accuracy: 0.8928571428571429, intent accuracy: 1.0
slot accuracy: 0.8911917098445595, intent accuracy: 0.9375
slot accuracy: 0.9090909090909091, intent accuracy: 0.9375
slot accuracy: 0.8854166666666666, intent accuracy: 0.9375
slot accuracy: 0.8492462311557789, intent accuracy: 0.875
slot accuracy: 0.8523809523809524, intent accuracy: 0.9375
slot accuracy

slot accuracy: 0.8947368421052632, intent accuracy: 0.9375
slot accuracy: 0.9520958083832335, intent accuracy: 0.875
slot accuracy: 0.9562841530054644, intent accuracy: 0.875
slot accuracy: 0.9435897435897436, intent accuracy: 0.875
slot accuracy: 0.9072164948453608, intent accuracy: 0.875
slot accuracy: 0.9444444444444444, intent accuracy: 0.875
slot accuracy: 0.9021739130434783, intent accuracy: 0.9375
slot accuracy: 0.900497512437811, intent accuracy: 0.75
slot accuracy: 0.9220183486238532, intent accuracy: 0.9375
slot accuracy: 0.9333333333333333, intent accuracy: 1.0
slot accuracy: 0.9205607476635514, intent accuracy: 0.9375
slot accuracy: 0.9114583333333334, intent accuracy: 0.9375
slot accuracy: 0.8761904761904762, intent accuracy: 0.9375
slot accuracy: 0.9393939393939394, intent accuracy: 0.875
slot accuracy: 0.9223744292237442, intent accuracy: 0.875
slot accuracy: 0.9197860962566845, intent accuracy: 0.9375
slot accuracy: 0.9528795811518325, intent accuracy: 0.875
slot accura

slot accuracy: 0.95, intent accuracy: 1.0
slot accuracy: 0.9230769230769231, intent accuracy: 0.875
slot accuracy: 0.8975609756097561, intent accuracy: 0.9375
slot accuracy: 0.9193548387096774, intent accuracy: 0.75
slot accuracy: 0.918918918918919, intent accuracy: 0.875
slot accuracy: 0.9251336898395722, intent accuracy: 0.8125
slot accuracy: 0.9301075268817204, intent accuracy: 0.875
slot accuracy: 0.949238578680203, intent accuracy: 0.875
[[2 2 2 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 ...
 [2 2 2 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 [2 2 2 ... 0 0 0]]
[[2 2 2 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 ...
 [2 2 2 ... 0 0 0]
 [2 2 2 ... 0 0 0]
 [2 2 2 ... 0 0 0]]
F1 score for epoch 6: 0.93348588863463
7
7
Average train loss at epoch 7, step 0: 0.641422
Average train loss at epoch 7, step 30: 0.347170
Average train loss at epoch 7, step 60: 0.305262
Average train loss at epoch 7, step 90: 0.291223
Average train loss at epoch 7, step 120: 0.323802
Average train loss at epo

Average train loss at epoch 8, step 120: 0.235707
Average train loss at epoch 8, step 150: 0.209873
Average train loss at epoch 8, step 180: 0.260408
Average train loss at epoch 8, step 210: 0.194084
[Epoch 8] Average train loss: 0.2184147656886676
Input Sentence        :  ['BOS', 'i', 'need', 'a', 'flight', 'leaving', 'pittsburgh', 'next', 'monday', 'arriving', 'in', 'fort', 'worth', 'before', '10', 'am', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>']
Slot Truth            :  ['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'B-depart_date.date_relative', 'B-depart_date.day_name', 'O', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'B-arrive_time.time_relative', 'B-arrive_time.time', 'I-arrive_time.time', 'O', '<PAD>', '<PAD>', 

slot accuracy: 0.9556650246305419, intent accuracy: 1.0
slot accuracy: 0.9502487562189055, intent accuracy: 0.875
slot accuracy: 0.9634703196347032, intent accuracy: 0.9375
slot accuracy: 0.9712918660287081, intent accuracy: 0.875
slot accuracy: 0.9299065420560748, intent accuracy: 0.9375
slot accuracy: 0.9384615384615385, intent accuracy: 1.0
slot accuracy: 0.9719626168224299, intent accuracy: 1.0
slot accuracy: 0.9466666666666667, intent accuracy: 0.75
slot accuracy: 0.945054945054945, intent accuracy: 0.9375
slot accuracy: 0.945273631840796, intent accuracy: 0.875
slot accuracy: 0.9748427672955975, intent accuracy: 0.875
slot accuracy: 0.949748743718593, intent accuracy: 0.875
slot accuracy: 0.9738219895287958, intent accuracy: 0.875
slot accuracy: 0.9166666666666666, intent accuracy: 1.0
slot accuracy: 0.949238578680203, intent accuracy: 1.0
slot accuracy: 0.9607843137254902, intent accuracy: 1.0
slot accuracy: 0.9711538461538461, intent accuracy: 1.0
slot accuracy: 0.9890109890109

slot accuracy: 0.9567099567099567, intent accuracy: 0.875
slot accuracy: 0.9895287958115183, intent accuracy: 0.875
slot accuracy: 0.9451476793248945, intent accuracy: 1.0
slot accuracy: 0.9603960396039604, intent accuracy: 0.9375
slot accuracy: 0.9292452830188679, intent accuracy: 0.875
slot accuracy: 0.9705882352941176, intent accuracy: 0.9375
slot accuracy: 0.9404761904761905, intent accuracy: 0.875
slot accuracy: 0.9463414634146341, intent accuracy: 0.9375
slot accuracy: 0.9481132075471698, intent accuracy: 1.0
slot accuracy: 0.9657142857142857, intent accuracy: 1.0
slot accuracy: 0.9723502304147466, intent accuracy: 1.0
slot accuracy: 0.9128205128205128, intent accuracy: 0.875
slot accuracy: 0.9734513274336283, intent accuracy: 1.0
slot accuracy: 0.9209302325581395, intent accuracy: 1.0
slot accuracy: 0.9395604395604396, intent accuracy: 0.875
slot accuracy: 0.8947368421052632, intent accuracy: 0.875
slot accuracy: 0.9797979797979798, intent accuracy: 0.9375
slot accuracy: 0.95336

slot accuracy: 0.9427083333333334, intent accuracy: 0.875
slot accuracy: 0.9760479041916168, intent accuracy: 0.8125
slot accuracy: 0.9471153846153846, intent accuracy: 0.8125
slot accuracy: 0.9739583333333334, intent accuracy: 0.875
slot accuracy: 0.9569377990430622, intent accuracy: 0.8125
slot accuracy: 0.9388888888888889, intent accuracy: 0.875
slot accuracy: 0.9585492227979274, intent accuracy: 0.9375
slot accuracy: 0.9565217391304348, intent accuracy: 1.0
slot accuracy: 0.9259259259259259, intent accuracy: 0.75
slot accuracy: 0.975609756097561, intent accuracy: 1.0
slot accuracy: 0.978021978021978, intent accuracy: 0.875
slot accuracy: 0.9478260869565217, intent accuracy: 0.875
slot accuracy: 0.9691358024691358, intent accuracy: 0.9375
slot accuracy: 0.9310344827586207, intent accuracy: 0.875
slot accuracy: 0.933649289099526, intent accuracy: 0.9375
slot accuracy: 0.9705882352941176, intent accuracy: 1.0
slot accuracy: 0.9635627530364372, intent accuracy: 0.875
slot accuracy: 0.9

slot accuracy: 0.9770642201834863, intent accuracy: 0.9375
slot accuracy: 0.9659090909090909, intent accuracy: 0.9375
slot accuracy: 0.9543147208121827, intent accuracy: 1.0
slot accuracy: 0.9842105263157894, intent accuracy: 0.875
slot accuracy: 0.9565217391304348, intent accuracy: 0.9375
slot accuracy: 0.9423076923076923, intent accuracy: 0.9375
slot accuracy: 0.946524064171123, intent accuracy: 0.9375
slot accuracy: 0.9611111111111111, intent accuracy: 1.0
slot accuracy: 0.9739583333333334, intent accuracy: 1.0
slot accuracy: 0.9655172413793104, intent accuracy: 0.8125
slot accuracy: 0.9494949494949495, intent accuracy: 0.9375
slot accuracy: 0.9723756906077348, intent accuracy: 0.9375
slot accuracy: 0.9523809523809523, intent accuracy: 1.0
slot accuracy: 0.946078431372549, intent accuracy: 1.0
slot accuracy: 0.9433962264150944, intent accuracy: 0.875
slot accuracy: 0.9372384937238494, intent accuracy: 0.9375
slot accuracy: 0.9709302325581395, intent accuracy: 0.8125
slot accuracy: 0

slot accuracy: 0.9649122807017544, intent accuracy: 0.875
slot accuracy: 0.9324324324324325, intent accuracy: 1.0
slot accuracy: 0.961352657004831, intent accuracy: 0.9375
slot accuracy: 0.9508196721311475, intent accuracy: 1.0
slot accuracy: 0.9897435897435898, intent accuracy: 0.9375
slot accuracy: 0.9210526315789473, intent accuracy: 0.875
slot accuracy: 0.9619565217391305, intent accuracy: 1.0
slot accuracy: 0.96875, intent accuracy: 1.0
slot accuracy: 0.9425837320574163, intent accuracy: 0.875
slot accuracy: 0.9388646288209607, intent accuracy: 1.0
slot accuracy: 0.9719626168224299, intent accuracy: 0.875
slot accuracy: 0.9226519337016574, intent accuracy: 0.9375
slot accuracy: 0.9844559585492227, intent accuracy: 1.0
slot accuracy: 0.9560975609756097, intent accuracy: 0.875
slot accuracy: 0.9772727272727273, intent accuracy: 0.875
slot accuracy: 0.9746192893401016, intent accuracy: 0.9375
slot accuracy: 0.95, intent accuracy: 0.8125
slot accuracy: 0.9669811320754716, intent accur

slot accuracy: 0.9638009049773756, intent accuracy: 0.875
slot accuracy: 0.9583333333333334, intent accuracy: 1.0
slot accuracy: 0.9526315789473684, intent accuracy: 0.9375
slot accuracy: 0.9251336898395722, intent accuracy: 0.9375
slot accuracy: 0.9835164835164835, intent accuracy: 0.9375
slot accuracy: 0.9912663755458515, intent accuracy: 1.0
slot accuracy: 0.9901477832512315, intent accuracy: 0.9375
slot accuracy: 0.9644670050761421, intent accuracy: 0.9375
slot accuracy: 0.9595959595959596, intent accuracy: 0.9375
slot accuracy: 0.9680365296803652, intent accuracy: 1.0
[[ 2 81  2 ...  0  0  0]
 [ 2  2  2 ...  0  0  0]
 [ 2  2  2 ...  0  0  0]
 ...
 [ 2  2  2 ...  0  0  0]
 [ 2  2  2 ...  0  0  0]
 [ 2  2  2 ...  0  0  0]]
[[ 2 81  2 ...  0  0  0]
 [ 2  2  2 ...  0  0  0]
 [ 2  2  2 ...  0  0  0]
 ...
 [ 2  2  2 ...  0  0  0]
 [ 2  2  2 ...  0  0  0]
 [ 2  2  2 ...  0  0  0]]
F1 score for epoch 14: 0.9644956860349697


In [23]:
#### Output prediction for the text you input manually
for j, batch in enumerate(getBatch2(batch_size, new_test_data)):
    decoder_prediction_v, intent_v = step(sess, "test", batch)
    decoder_prediction_v = np.transpose(decoder_prediction_v, [1, 0])
    #if j == 54:
    for index in range(16):
        #index = 15 
        #print("Your Sentence is      : ", my_sentence, "\n")
        print("Input Sentence        : ", index_seq2word(batch[index][0], index2word), "\n")
        print("Slot Prediction       : ", index_seq2slot(decoder_prediction_v[index], index2tag), "\n")
        print("Intent Prediction     : ", index2intent[intent_v[index]])

Input Sentence        :  ['BOS', 'i', 'would', 'like', 'to', 'find', 'a', 'flight', 'from', 'charlotte', 'to', 'las', 'vegas', 'that', 'makes', 'a', 'stop', 'in', 'st.', 'louis', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'O', 'O', 'O', 'O', 'O', 'B-stoploc.city_name', 'I-stoploc.city_name', 'O', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'on', 'april', 'first', 'i', 'need', 'a', 'ticket', 'from', 'tacoma', 'to', 'san', 'jose', 'departing', 'before', '7', 'am', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', 

Input Sentence        :  ['BOS', 'does', 'tacoma', 'airport', 'offer', 'transportation', 'from', 'the', 'airport', 'to', 'the', 'downtown', 'area', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'B-city_name', 'I-airport_name', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-transport_type', 'O', '<PAD>', '<PAD>'] 

Intent Prediction     :  ground_service
Input Sentence        :  ['BOS', 'which', 'flights', 'travel', 'from', 'tacoma', 'to', 'san', 'jose', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', 

Input Sentence        :  ['BOS', 'which', 'flights', 'leave', 'chicago', 'on', 'april', 'twelfth', 'and', 'arrive', 'in', 'indianapolis', 'in', 'the', 'morning', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-depart_date.day_name', 'B-depart_date.day_number', 'O', 'O', 'O', 'B-toloc.city_name', 'O', 'O', 'B-arrive_time.period_of_day', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'which', 'flights', 'leave', 'on', 'wednesday', 'april', 'thirteenth', 'from', 'indianapolis', 'and', 'arrive',

Input Sentence        :  ['BOS', 'which', 'flights', 'arrive', 'in', 'burbank', 'from', 'las', 'vegas', 'on', 'saturday', 'april', 'twenty', 'third', 'in', 'the', 'afternoon', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'B-toloc.city_name', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-depart_date.day_name', 'B-arrive_date.month_name', 'B-arrive_date.day_number', 'I-depart_date.day_number', 'O', 'O', 'B-depart_time.period_of_day', 'O', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'which', 'flights', 'are', 'available', 'from', 'orlando', 'to', 'cleveland', 'that', 'arrive', 'around', '10', 'pm', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>

Input Sentence        :  ['BOS', 'show', 'me', 'all', 'the', 'flights', 'from', 'las', 'vegas', 'to', 'new', 'york', 'city', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'O', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'which', 'different', 'airlines', 'go', 'from', 'las', 'vegas', 'to', 'new', 'york', 'city', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PA

Input Sentence        :  ['BOS', 'list', 'the', 'flights', 'from', 'dallas', 'to', 'baltimore', 'arriving', 'july', 'first', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'B-arrive_date.month_name', 'B-arrive_date.day_number', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'list', 'the', 'flights', 'from', 'pittsburgh', 'to', 'baltimore', 'arriving', 'on', 'july', 'first', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<

Input Sentence        :  ['BOS', 'how', 'far', 'is', 'los', 'angeles', 'international', 'from', 'downtown', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'B-airport_name', 'I-airport_name', 'I-airport_name', 'O', 'O', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  distance
Input Sentence        :  ['BOS', 'how', 'far', 'is', 'san', 'francisco', 'international', 'from', 'downtown', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<P

Input Sentence        :  ['BOS', 'list', 'flights', 'from', 'philadelphia', 'to', 'atlanta', 'friday', 'am', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'B-depart_date.month_name', 'B-depart_date.day_number', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'list', 'flights', 'from', 'atlanta', 'to', 'toronto', 'friday', 'afternoon', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'

Input Sentence        :  ['BOS', 'list', 'flights', 'from', 'ontario', 'california', 'to', 'salt', 'lake', 'city', 'utah', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'B-fromloc.city_name', 'B-fromloc.state_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'I-toloc.city_name', 'B-toloc.state_name', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'list', 'flights', 'from', 'ontario', 'california', 'to', 'salt', 'lake', 'city', 'utah', 'monday', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<

Input Sentence        :  ['BOS', 'i', 'would', 'like', 'flights', 'from', 'san', 'diego', 'to', 'las', 'vegas', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'i', 'would', 'like', 'a', 'flight', 'from', 'san', 'diego', 'to', 'las', 'vegas', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '

Input Sentence        :  ['BOS', 'show', 'me', 'flights', 'from', 'montreal', 'to', 'orlando', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'i', 'need', 'a', 'flight', 'on', 'friday', 'afternoon', 'in', 'june', 'from', 'new', 'york', 'to', 'cleveland', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '

Input Sentence        :  ['BOS', 'what', "'s", 'the', 'cheapest', 'flight', 'tomorrow', 'from', 'milwaukee', 'to', 'denver', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'B-cost_relative', 'O', 'B-depart_date.today_relative', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'what', 'ground', 'transportation', 'is', 'available', 'at', 'denver', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<

Input Sentence        :  ['BOS', 'what', 'ground', 'transportation', 'is', 'available', 'between', 'phoenix', 'airport', 'and', 'downtown', 'phoenix', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.airport_name', 'I-fromloc.airport_name', 'O', 'O', 'B-toloc.city_name', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  ground_service
Input Sentence        :  ['BOS', 'what', 'is', 'the', 'seating', 'capacity', 'for', 'the', 'aircraft', 'm80', 'EOS', '<PAD>', '<PAD>', '<PAD>', '

Input Sentence        :  ['BOS', 'i', 'would', 'like', 'to', 'fly', 'from', 'san', 'diego', 'to', 'seattle', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'i', 'would', 'like', 'to', 'fly', 'from', 'orlando', 'to', 'kansas', 'city', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'

Input Sentence        :  ['BOS', 'show', 'flights', 'from', 'kansas', 'city', 'to', 'minneapolis', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'show', 'flights', 'from', 'kansas', 'city', 'to', 'orlando', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<P

Input Sentence        :  ['BOS', 'get', 'fares', 'from', 'washington', 'to', 'boston', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  airfare
Input Sentence        :  ['BOS', 'get', 'saturday', 'fares', 'from', 'washington', 'to', 'boston', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'i', 'need', 'a', 'flight', 'departing', 'from', 'milwaukee', 'to', 'indianapolis', 'leaving', 'monday', 'before', '8', 'am', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'B-depart_date.day_name', 'B-depart_time.time_relative', 'B-depart_time.time', 'I-depart_time.time', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'is', 'there', 'ground', 'transportation', 'available', 'at', 'the', 'indianapolis', 'airport', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PA

Input Sentence        :  ['BOS', 'what', 'is', '<UNK>', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'B-airport_code', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  abbreviation
Input Sentence        :  ['BOS', 'what', 'are', 'the', 'flights', 'from', 'cleveland', 'to', 'dallas', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'please', 'list', 'all', 'flights', 'from', 'new', 'york', 'to', 'miami', 'any', 'any', 'type', 'of', 'class', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'O', 'O', 'O', 'B-round_trip', 'O'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'what', 'does', 'fare', 'code', '<UNK>', 'mean', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '

Input Sentence        :  ['BOS', 'st.', 'petersburg', 'to', 'detroit', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'from', 'milwaukee', 'to', 'orlando', 'one', 'way', 'after', '5', 'pm', 'wednesday', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'list', 'flights', 'from', 'chicago', 'to', 'san', 'diego', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'O', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'list', 'flights', 'from', 'kansas', 'city', 'to', 'denver', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'

Input Sentence        :  ['BOS', 'list', 'flights', 'from', 'charlotte', 'on', 'saturday', 'afternoon', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-depart_date.day_name', 'B-depart_time.period_of_day', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'list', 'type', 'of', 'aircraft', 'for', 'all', 'flights', 'from', 'charlotte', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<P

Input Sentence        :  ['BOS', 'give', 'me', 'flights', 'from', 'seattle', 'to', 'chicago', 'that', 'have', 'meals', 'on', 'continental', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'O', 'B-mod', 'O', 'B-airline_name', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'give', 'me', 'the', 'flights', 'from', 'seattle', 'to', 'chicago', 'that', 'have', 'meals', 'on', 'continental', 'saturday', 'morning', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'

Slot Prediction       :  ['O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'B-depart_date.day_name', 'O', 'B-arrive_time.time_relative', 'B-arrive_time.time', 'I-arrive_time.time', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'miami', 'to', 'cleveland', 'sunday', 'afternoon', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'B-depart_date.day_name', 'B-depart_time.period_of_day', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input 

Input Sentence        :  ['BOS', 'show', 'me', 'the', 'first', 'class', 'and', 'coach', 'flights', 'from', 'jfk', 'to', 'miami', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'B-class_type', 'I-class_type', 'O', 'B-flight_mod', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'are', 'meals', '<UNK>', 'served', 'on', 'tower', 'air', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '

Input Sentence        :  ['BOS', 'list', 'all', 'flights', 'arriving', 'in', 'denver', 'between', '8', 'and', '9', 'pm', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'O', 'B-toloc.city_name', 'O', 'B-depart_time.start_time', 'O', 'B-arrive_time.time', 'I-arrive_time.time', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'what', 'is', 'the', 'capacity', 'of', 'the', '73s', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<P

Input Sentence        :  ['BOS', 'what', 'are', 'the', 'nonstop', 'flights', 'from', 'cincinnati', 'to', 'charlotte', 'leaving', 'after', 'noon', 'and', 'arriving', 'before', '7', 'pm', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'B-flight_stop', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'B-depart_time.time_relative', 'B-depart_time.time', 'O', 'O', 'B-arrive_time.time_relative', 'B-arrive_time.time', 'I-arrive_time.time', 'O'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'how', 'many', 'flights', 'does', 'alaska', 'airlines', 'have', 'to', 'burbank', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<

Input Sentence        :  ['BOS', 'what', 'are', 'the', 'flights', 'from', 'phoenix', 'arizona', 'to', 'st.', 'paul', 'minnesota', 'on', 'tuesday', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'B-fromloc.state_name', 'O', 'B-toloc.city_name', 'I-toloc.city_name', 'B-toloc.state_name', 'O', 'B-depart_date.day_name', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'what', 'are', 'the', 'flights', 'on', 'thursday', 'leaving', 'from', 'st.', 'paul', 'minnesota', 'to', 'st.', 'louis', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '

Input Sentence        :  ['BOS', 'i', "'d", 'like', 'a', 'round', 'trip', 'flight', 'from', 'kansas', 'city', 'to', 'chicago', 'on', 'wednesday', 'may', 'twenty', 'sixth', 'arriving', 'at', '7', 'pm', 'EOS', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Slot Prediction       :  ['O', 'O', 'O', 'O', 'O', 'B-round_trip', 'I-round_trip', 'O', 'O', 'B-fromloc.city_name', 'I-fromloc.city_name', 'O', 'B-toloc.city_name', 'O', 'B-depart_date.day_name', 'B-depart_date.month_name', 'B-depart_date.day_number', 'I-depart_date.day_number', 'O', 'O', 'B-arrive_time.time', 'I-arrive_time.time', 'O', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

Intent Prediction     :  flight
Input Sentence        :  ['BOS', 'yes', 'i', "'d", 'like', 'to', 'find', 'a', 'flight', 'from', 'memph